/**
 * Terceiro lote sintético — 470 relatos com sotaque potiguar, todos inéditos.
 *
 * Escritos em linguagem popular de Natal e Parnamirim/RN, como a pessoa fala na recepção da
 * UBS, da USF e da UPA. A maior parte (~370) é demanda comum da Atenção Básica; o restante
 * são urgências, emergências, arbovirose, violência e ruído.
 *
 * MÉTODO — escrito sem consultar `criterios.ts`. Ressalva honesta: quem escreveu já trabalhou
 * neste catálogo antes, então a cegueira é PARCIAL. A taxa de reconhecimento medida aqui é
 * provavelmente otimista frente a um lote escrito por quem nunca viu o código. O teste que
 * vale de verdade continua sendo o do achado A1/B11: rodar sobre relatos históricos REAIS do
 * acolhimento, antes de ligar o sistema.
 *
 * Contexto local que aparece nos relatos: calor o ano todo, maresia e praia, arbovirose
 * endêmica, muita moto, trabalho informal (feirante, pedreiro, motoboy, pescador, doméstica).
 *
 *   npm run auditar -- testes/lote-sintetico-rn.ts
 */

export interface Caso {
  relato: string;
  idade?: number;
  agravantes?: string[];
  inicioMenos24h?: boolean;
  paraQuem?: 'proprio' | 'terceiro';
  grupo: string;
}

const c = (
  relato: string,
  grupo: string,
  idade?: number,
  agravantes: string[] = [],
  inicioMenos24h = false,
): Caso => ({ relato, grupo, idade, agravantes, inicioMenos24h });

export const LOTE: Caso[] = [
  // ══════════════════════════ COMUM ══════════════════════════
  // ── Respiratório e ORL (42) ──
  c('oxe, amanheci com a garganta ardendo demais', 'resp', 27, [], true),
  c('to com um resfriado danado, o nariz num para de pingar', 'resp', 34),
  c('peguei essa gripe que ta rolando no trabalho', 'resp', 41),
  c('minha garganta ta doendo pra engolir até água', 'resp', 23),
  c('to com uma tosse braba que num me deixa dormir de noite', 'resp', 46),
  c('tossindo e saindo um catarro esverdeado', 'resp', 52),
  c('minha venta ta trancada e num sinto cheiro de nada', 'resp', 38),
  c('to com dor na testa e no rosto, deve ser da sinusite', 'resp', 44),
  c('fiquei sem voz de tanto gritar na feira', 'resp', 49),
  c('minha filhinha ta chiando quando respira de noite', 'resp', 4),
  c('o menino pegou uma tossizinha na escola', 'resp', 6),
  c('meu ouvido ta tampado depois que fui na praia', 'orl', 25),
  c('to com uma dor de ouvido que num passa com nada', 'orl', 19, [], true),
  c('meu ouvido ta apitando direto, num descanso', 'orl', 58),
  c('num to ouvindo direito desse ouvido esquerdo', 'orl', 64),
  c('saiu um liquido do meu ouvido depois do banho de mar', 'orl', 22),
  c('meu nariz sangrou hoje cedo, com esse calor todo', 'orl', 31, [], true),
  c('to espirrando desde que a poeira subiu na obra', 'resp', 36),
  c('minha alergia atacou de novo, num paro de espirrar', 'resp', 29),
  c('to com o peito carregado, cheio de catarro', 'resp', 55),
  c('to gastando muita bombinha esse mês', 'resp', 33, ['asma_dpoc']),
  c('meu peito assobia quando eu deito pra dormir', 'resp', 47, ['asma_dpoc']),
  c('to com a garganta cheia de bolinha branca', 'resp', 21),
  c('minha garganta inflama toda vez que muda o tempo', 'resp', 32),
  c('to rouco faz uns quatro dias e num melhora', 'resp', 43),
  c('meu nenem ta com o narizinho entupido e num mama direito', 'resp', 0, ['crianca_menor_2']),
  c('a menina ta com o nariz escorrendo e espirrando', 'resp', 3),
  c('to com uma canseirinha quando subo a ladeira', 'resp', 61, ['hipertensao']),
  c('meu marido ronca demais e para de respirar dormindo', 'orl', 52),
  c('to com afta na boca que num sara', 'orl', 28),
  c('minha lingua ta branca e o gosto ta ruim', 'orl', 40),
  c('to com um bafo ruim e num sei o motivo', 'orl', 35),
  c('minha gengiva sangra toda vez que escovo o dente', 'orl', 39),
  c('apareceu uma bolinha dentro da minha bochecha', 'orl', 30),
  c('to sentindo o ouvido cheio de cera', 'orl', 57),
  c('minha garganta arranha quando falo muito', 'resp', 26),
  c('to com defluxo e uma dor no corpo leve', 'resp', 45),
  c('peguei friagem no ar condicionado do ônibus', 'resp', 37),
  c('to tossindo e sinto uma pontada nas costelas quando tusso', 'resp', 50),
  c('minha nenem ta com o peito roncando', 'resp', 1, ['crianca_menor_2']),
  c('to com o nariz coçando e os olhos lacrimejando', 'resp', 24),
  c('meu filho vive gripado, é uma atrás da outra', 'resp', 5),

  // ── Musculoesquelético e trauma leve (42) ──
  c('minha coluna ta quebrada de carregar caixa na feira', 'musculo', 44),
  c('acordei com o pescoço travado, num viro a cabeça', 'musculo', 39, [], true),
  c('to com uma dor no cocuruto das costas faz dias', 'musculo', 51),
  c('meu joelho incha toda vez que ando muito', 'musculo', 58),
  c('num consigo levantar o braço pra pentear o cabelo', 'musculo', 54),
  c('torci o pé no buraco da calçada ontem', 'musculo', 32, [], true),
  c('minha mão dói de tanto lavar roupa pros outros', 'musculo', 47),
  c('to com dor nas cadeiras que num me deixa dormir de lado', 'musculo', 62),
  c('meus dedos amanhecem duros, custa a abrir a mão', 'musculo', 60),
  c('meu calcanhar arde quando piso de manhã cedo', 'musculo', 45),
  c('to com caimbra na perna toda madrugada', 'musculo', 55),
  c('caí da escada no trabalho e ralei o braço todo', 'trauma', 29, [], true),
  c('bati o dedão do pé na quina do sofá', 'trauma', 36, [], true),
  c('meu filho caiu do balanço e esfolou o joelho', 'trauma', 8, [], true),
  c('prensei a mão no portão de ferro', 'trauma', 41, [], true),
  c('to com a lombar travada de dormir em rede', 'musculo', 48),
  c('minhas costas doem de ficar em pé o dia todo vendendo', 'musculo', 43),
  c('minhas mãos formigam de noite, acordo sem sentir', 'musculo', 52),
  c('sinto uma agulhada na coluna quando me abaixo', 'musculo', 46),
  c('minhas pernas incham de tanto ficar em pé no balcão', 'musculo', 40),
  c('to com as varizes ardendo e as pernas pesadas', 'musculo', 56),
  c('meu pé dorme e formiga por causa da diabete', 'musculo', 63, ['diabetes']),
  c('torci o punho jogando futebol de areia', 'trauma', 24, [], true),
  c('bati a cabeça de leve na porta do ônibus, sem tontura', 'trauma', 33, [], true),
  c('meu ombro estala e dói quando levanto peso na obra', 'musculo', 38),
  c('a sola do meu pé arde de andar descalço na areia quente', 'musculo', 30),
  c('minha mão amanhece inchada e formigando', 'musculo', 53),
  c('to com dor no quadril quando subo no ônibus', 'musculo', 66),
  c('o médico falou que é bursite no meu ombro', 'musculo', 59),
  c('meu joelho falha e quase caio quando ando', 'musculo', 57),
  c('caí sentado na laje e to com dor no fim da coluna', 'trauma', 34, [], true),
  c('puxei o músculo da coxa correndo na praia', 'musculo', 27, [], true),
  c('meu braço ta doendo desde que carreguei o gás', 'musculo', 42),
  c('minha nuca dói de ficar olhando o celular', 'musculo', 25),
  c('to com o pulso doendo de trabalhar na costura', 'musculo', 49),
  c('minha canela ta roxa de bater na moto', 'trauma', 28, [], true),
  c('to com um estiramento no ombro de puxar rede de pesca', 'musculo', 44),
  c('meu tornozelo incha no fim do dia', 'musculo', 61, ['hipertensao']),
  c('minhas juntas doem quando o tempo vira pra chuva', 'musculo', 67),
  c('to com dor no cotovelo de bater massa de bolo', 'musculo', 50),
  c('meu dedo ta preso e num dobra direito', 'musculo', 58),
  c('bati o pé na pedra da calçada e ta inchado', 'trauma', 46, [], true),

  // ── Dermatologia (35) ──
  c('to com uma coceira danada no corpo com esse calor', 'derm', 33),
  c('to cheia de brotoeja nas dobras do braço', 'derm', 28),
  c('meu filho ta cheio de bolinha vermelha coçando', 'derm', 5),
  c('peguei uma micose na unha do pé', 'derm', 40),
  c('to com um calo na sola do pé que dói pra andar', 'derm', 45),
  c('minha unha do pé encravou e ta latejando', 'derm', 37),
  c('apareceu uma mancha escura no meu rosto depois da praia', 'derm', 42),
  c('to com caspa e o couro cabeludo coçando', 'derm', 34),
  c('minha pele descama entre as pernas de suor', 'derm', 47),
  c('apareceu um caroço no meu pescoço', 'derm', 31),
  c('tenho uma pinta nas costas que ta mudando de cor', 'derm', 55),
  c('minha nenem ta com a bunda assada e vermelha', 'derm', 0, ['crianca_menor_2']),
  c('fui picado por muriçoca e inchou tudo', 'derm', 26, [], true),
  c('to com uma frieira que descasca e coça', 'derm', 43),
  c('to cheio de espinha no rosto e nas costas', 'derm', 17),
  c('me queimei de sol na praia e a pele ta empolando', 'derm', 24, [], true),
  c('apareceu uma bolha de água na minha mão do nada', 'derm', 36),
  c('to com uma coceira braba na virilha', 'derm', 38),
  c('a pele do meu nenem ta ressecada e ardida', 'derm', 1, ['crianca_menor_2']),
  c('apareceu uma placa vermelha e áspera no meu braço', 'derm', 41),
  c('minha ferida antiga voltou a inflamar', 'derm', 49),
  c('to com um furúnculo na coxa cheio de pus', 'derm', 35),
  c('apareceu um cobreiro nas minhas costas ardendo', 'derm', 54),
  c('minha pele ta com umas manchas brancas nos braços', 'derm', 30),
  c('minhas mãos tão rachadas de mexer com material de limpeza', 'derm', 46),
  c('apareceu uma verruguinha no meu pescoço', 'derm', 39),
  c('to com o pé descascando e fedendo', 'derm', 32),
  c('minha filha ta cheia de bolinha de catapora', 'derm', 7),
  c('to com sarna, coça mais de noite', 'derm', 12),
  c('a criançada da casa toda ta com coceira igual', 'derm', 9),
  c('encostei numa água-viva na praia e ta ardendo', 'derm', 21, [], true),
  c('to com uma queimadura de sol que ta descascando', 'derm', 27),
  c('apareceu uma bolinha no meu olho, tipo um carocinho', 'derm', 29),
  c('minha canela ta cheia de mancha escura da diabete', 'derm', 60, ['diabetes']),
  c('to com um calombo no braço onde a muriçoca picou', 'derm', 33),

  // ── Gastrointestinal (36) ──
  c('to com azia toda vez que como buchada', 'gastro', 45),
  c('sinto uma queimação no estômago de madrugada', 'gastro', 50),
  c('minha gastrite atacou de tanto nervoso', 'gastro', 37),
  c('meu estômago ta embrulhado desde que comi na feira', 'gastro', 31, [], true),
  c('to com uma diarreia que num para desde ontem', 'gastro', 28, [], true),
  c('to com o intestino preso faz uns cinco dias', 'gastro', 59),
  c('meu filho ta com desarranjo e uma febrinha', 'gastro', 4, [], true),
  c('to estufada e cheia de gases', 'gastro', 43),
  c('vomitei o almoço e depois melhorei', 'gastro', 32, [], true),
  c('to enjoada, acho que a comida tava estragada', 'gastro', 26, [], true),
  c('minha barriga dói de leve e vai e volta', 'gastro', 34),
  c('to com uma cólica no pé da barriga desde ontem', 'gastro', 40, [], true),
  c('to com hemorroida e sangra quando vou no banheiro', 'gastro', 46),
  c('sai um pinguinho de sangue no papel quando limpo', 'gastro', 38),
  c('meu intestino ta trancado e a barriga dura', 'gastro', 54),
  c('to com soluço faz umas duas horas e num para', 'gastro', 33),
  c('meu estômago rói quando fico sem comer', 'gastro', 44),
  c('meu menino reclama de dor na barriga toda manhã de aula', 'gastro', 9),
  c('a comida volta na minha garganta quando deito', 'gastro', 51),
  c('to com diarreia depois que comi camarão', 'gastro', 29, [], true),
  c('minha barriga ronca e ta solta faz dias', 'gastro', 35),
  c('perdi a fome e to emagrecendo sem querer', 'gastro', 57),
  c('to com ânsia mas num vomito nada', 'gastro', 30),
  c('meu bebê golfa tudo depois que mama', 'gastro', 0, ['crianca_menor_2']),
  c('sinto um aperto em cima da barriga depois de comer', 'gastro', 48),
  c('num consigo fazer cocô sem forçar demais', 'gastro', 61),
  c('to com verme, sinto coceira no fiofó de noite', 'gastro', 11),
  c('minha filha range o dente dormindo, deve ser lombriga', 'gastro', 6),
  c('comi demais no aniversário e passei mal', 'gastro', 39, [], true),
  c('to com gastura e vontade de botar pra fora', 'gastro', 42),
  c('minha digestão ta pesada, demoro a esvaziar', 'gastro', 52),
  c('meu estômago dói quando tomo remédio de barriga vazia', 'gastro', 56),
  c('to com dor de barriga e febre baixinha faz dois dias', 'gastro', 27),
  c('to com o intestino preso desde que mudei a comida', 'gastro', 36),
  c('minha barriga incha depois que como macaxeira', 'gastro', 41),
  c('to com queimação e um gosto amargo na boca', 'gastro', 47),

  // ── Urinário e genital (28) ──
  c('to com uma ardência quando faço xixi', 'urin', 25),
  c('to indo no banheiro de cinco em cinco minutos', 'urin', 32),
  c('meu xixi ta escuro e com cheiro forte', 'urin', 47),
  c('acho que peguei infecção urinária de novo', 'urin', 38),
  c('to urinando pouquinho e ardendo demais', 'urin', 43),
  c('meu marido levanta umas cinco vezes de noite pra urinar', 'urin', 65),
  c('to com um peso no pé da barriga e vontade de urinar', 'urin', 34),
  c('minha filha voltou a fazer xixi na cama com nove anos', 'urin', 9),
  c('to com um corrimento branco e coçando', 'genital', 27),
  c('to menstruando demais, troco absorvente toda hora', 'genital', 42),
  c('to sem menstruar faz quatro meses e num to grávida', 'genital', 45),
  c('to com uma coceira na parte de baixo', 'genital', 30),
  c('apareceu uma ferida na minha parte íntima', 'genital', 23),
  c('sinto dor quando tenho relação com meu marido', 'genital', 36),
  c('to com um corrimento amarelo e com cheiro', 'genital', 28),
  c('meu marido ta com ardência pra urinar e saindo pus', 'genital', 33),
  c('minha regra ta desregulada esse ano todo', 'genital', 40),
  c('to com cólica menstrual que me dobra', 'genital', 21),
  c('apareceu umas verruguinhas na minha parte íntima', 'genital', 26),
  c('sinto que minha bexiga num esvazia tudo', 'urin', 58),
  c('to com vontade mas sai só um pinguinho', 'urin', 50),
  c('sinto um peso embaixo, parece que ta caindo', 'genital', 54),
  c('to grávida e com ardência pra fazer xixi', 'genital', 24),
  c('meu menino chora quando faz xixi', 'urin', 5),
  c('apareceu um caroço na minha virilha que dói', 'genital', 37),
  c('to com o saco coçando e vermelho', 'genital', 31),
  c('meu xixi saiu com um cheiro de remédio', 'urin', 44),
  c('to com dor nos ovários, é o que eu acho', 'genital', 29),

  // ── Saúde mental leve (26) ──
  c('to muito aperreada com as coisas da vida', 'mental', 35),
  c('num consigo dormir de tanto pensar nas contas', 'mental', 43),
  c('to numa tristeza que num passa de jeito nenhum', 'mental', 39),
  c('queria muito conversar com uma psicóloga', 'mental', 28),
  c('to explodindo com todo mundo em casa', 'mental', 46),
  c('meu peito bate acelerado quando me aperreio', 'mental', 32),
  c('acho que to com depressão, num tenho vontade de nada', 'mental', 41),
  c('acabou meu remédio de dormir', 'mental', 48),
  c('minha cabeça num para, é pensamento atrás de pensamento', 'mental', 37),
  c('durmo demais e mesmo assim acordo cansada', 'mental', 34),
  c('to comendo demais por causa da ansiedade', 'mental', 29),
  c('meu filho de quinze anos só fica trancado no quarto', 'mental', 15),
  c('num tenho ânimo nem pra tomar banho', 'mental', 45),
  c('to chorando à toa esses dias todos', 'mental', 38),
  c('vivo esquecendo as coisas e isso me preocupa', 'mental', 60),
  c('to bebendo todo fim de semana e queria parar', 'mental', 49),
  c('meu marido bebe demais e a casa num aguenta mais', 'mental', 47),
  c('me deu um aperto no peito e um medo de morrer do nada', 'mental', 30),
  c('num consigo focar em nada, minha cabeça viaja', 'mental', 26),
  c('to com insônia desde que perdi o emprego', 'mental', 36),
  c('sinto medo de sair sozinha na rua', 'mental', 33),
  c('to com pensamento ruim mas num faria nada, juro', 'mental', 42),
  c('minha filha adolescente anda muito calada e triste', 'mental', 16),
  c('to nervosa demais, qualquer coisa me irrita', 'mental', 40),
  c('minha vó ta esquecida e repete a mesma pergunta', 'mental', 78),
  c('to fumando demais pra dar conta do estresse', 'mental', 44),

  // ── Pediatria comum (35) ──
  c('meu filho amanheceu quentinho de febre', 'ped', 3, [], true),
  c('a nenem ta com quentura e chorosa', 'ped', 1, ['crianca_menor_2'], true),
  c('meu menino ta tossindo e chiando o peito', 'ped', 5),
  c('minha filha vomitou umas quatro vezes hoje', 'ped', 6, [], true),
  c('o bebê ta com desarranjo e a bundinha assada', 'ped', 1, ['crianca_menor_2']),
  c('meu filho num quis almoçar e ta manhoso', 'ped', 4),
  c('a criança ta com o olho vermelho e grudando de manhã', 'ped', 5),
  c('meu menino ta puxando a orelha e chorando', 'ped', 2, ['crianca_menor_2']),
  c('a menina pegou piolho na escola de novo', 'ped', 8),
  c('meu bebê ta com uma placa branca na boquinha', 'ped', 0, ['crianca_menor_2']),
  c('minha filha ta com uma tosse que parece latido', 'ped', 2, ['crianca_menor_2']),
  c('o nenem nasceu e vim fazer a primeira consulta', 'ped', 0, ['crianca_menor_2']),
  c('meu filho ta com umas manchinhas e febre', 'ped', 4),
  c('a criança num ta engordando direito', 'ped', 1, ['crianca_menor_2']),
  c('meu bebê chora de cólica a noite toda', 'ped', 0, ['crianca_menor_2']),
  c('meu filho engasgou com leite mas passou logo', 'ped', 0, ['crianca_menor_2']),
  c('a menina ta com dor de barriga e sem fazer cocô', 'ped', 7),
  c('meu filho vive coçando a cabeça', 'ped', 6),
  c('vim vacinar meu bebê que ta na idade', 'ped', 0, ['crianca_menor_2']),
  c('a criança ta com o nariz cheio e roncando pra respirar', 'ped', 2, ['crianca_menor_2']),
  c('meu filho caiu e bateu o queixo, ta chorando muito', 'ped', 3, [], true),
  c('minha filha reclama de dor nas perninhas de noite', 'ped', 5),
  c('o umbigo do meu nenem ta vermelho e com cheiro', 'ped', 0, ['crianca_menor_2']),
  c('meu menino ainda molha a cama com dez anos', 'ped', 10),
  c('minha filha ta com verruga na mãozinha', 'ped', 7),
  c('os olhinhos do bebê tão lacrimejando muito', 'ped', 0, ['crianca_menor_2']),
  c('meu filho ta gaguejando e a professora falou comigo', 'ped', 5),
  c('a criança comeu terra no quintal e to preocupada', 'ped', 3),
  c('meu menino ta com o dente de leite mole', 'ped', 6),
  c('minha filha reclama que num enxerga o quadro na escola', 'ped', 8),
  c('meu bebê ta com o peito chiando e mama pouco', 'ped', 1, ['crianca_menor_2']),
  c('a menina ta com uma bolinha atrás da orelha', 'ped', 4),
  c('meu filho ta com o cocô esbranquiçado', 'ped', 2, ['crianca_menor_2']),
  c('a criança ta com a barriga inchada e magrinha', 'ped', 5),
  c('meu filho tem medo de ir na escola e chora todo dia', 'ped', 6),

  // ── Crônicos e idoso (42) ──
  c('vim pegar a receita nova do remédio da pressão', 'cronico', 63, ['hipertensao']),
  c('acabou meu remédio de diabete', 'cronico', 57, ['diabetes']),
  c('medi a pressão na farmácia e deu dezesseis por dez', 'cronico', 61, ['hipertensao']),
  c('minha pressão amanheceu alta de novo', 'cronico', 66, ['hipertensao']),
  c('meu açúcar amanheceu em duzentos e cinquenta', 'cronico', 54, ['diabetes']),
  c('to com muita sede e urinando o tempo todo', 'cronico', 48, ['diabetes']),
  c('vim na consulta de rotina da diabete', 'cronico', 60, ['diabetes']),
  c('quero saber o resultado do meu colesterol', 'cronico', 52),
  c('o médico pediu pra acompanhar minha tireoide', 'cronico', 43),
  c('to tomando o remédio da pressão mas me deixa tonto', 'cronico', 68, ['hipertensao']),
  c('minha diabete ta desregulada esse mês todo', 'cronico', 58, ['diabetes']),
  c('vim pegar minha insulina na farmácia daqui', 'cronico', 56, ['diabetes']),
  c('preciso das fitinha de medir o açúcar', 'cronico', 62, ['diabetes']),
  c('minha vó de oitenta anos num quer comer nada', 'idoso', 80),
  c('painho ta mais esquecido e às vezes num reconhece a gente', 'idoso', 79),
  c('mainha caiu no quintal ontem e ta dolorida', 'idoso', 74, [], true),
  c('meu sogro que fica de cama ta com uma ferida no bumbum', 'idoso', 83, ['acamado']),
  c('minha vó num dorme de noite e fica agitada', 'idoso', 81),
  c('painho toma uns dez remédio e vive zonzo', 'idoso', 76, ['hipertensao', 'diabetes']),
  c('a perna da minha mãe ta inchada só de um lado', 'idoso', 77),
  c('meu avô cansa só de andar até o portão', 'idoso', 82, ['cardiopatia']),
  c('minha sogra esquece de tomar os remédios', 'idoso', 75),
  c('painho ta enxergando embaçado por causa da diabete', 'idoso', 71, ['diabetes']),
  c('minha vó fica tonta quando levanta da rede', 'idoso', 84),
  c('meu tio ta amarelo dos olhos', 'cronico', 57),
  c('meu exame deu colesterol e triglicerídeo alto', 'cronico', 45),
  c('minha pressão sobe toda vez que fico nervosa', 'cronico', 50, ['hipertensao']),
  c('vim medir a pressão que to com dor na nuca', 'cronico', 58, ['hipertensao']),
  c('meu marido diabético ta com uma ferida no pé', 'cronico', 64, ['diabetes']),
  c('meus pés formigam por causa da diabete', 'cronico', 61, ['diabetes']),
  c('mainha num quer beber água nem comer', 'idoso', 86),
  c('painho ta urinando pouco e as pernas incharam', 'idoso', 73, ['hipertensao']),
  c('minha vó diz que o coração dispara às vezes', 'idoso', 78, ['cardiopatia']),
  c('to com a pressão baixa e me sinto fraco', 'cronico', 47),
  c('acabou meu remédio de pressão e a cabeça ta doendo', 'cronico', 55, ['hipertensao']),
  c('minha sogra acamada ta com o cocô preso faz dias', 'idoso', 85, ['acamado']),
  c('painho ta com a boca torta desde ano passado, quero fisio', 'idoso', 70),
  c('minha vó ta com dor no corpo todo e num quer levantar', 'idoso', 79),
  c('vim buscar fralda geriátrica pra minha mãe', 'idoso', 82, ['acamado']),
  c('meu pai perdeu peso e a roupa ta larga nele', 'idoso', 76),
  c('minha mãe tosse toda vez que bebe água', 'idoso', 80),
  c('painho ta com uma unha do pé grossa e amarelada', 'idoso', 74, ['diabetes']),

  // ── Mulher: gestação, puerpério, planejamento (28) ──
  c('descobri que to grávida e quero começar o pré natal', 'mulher', 26),
  c('to de três meses e enjoando o dia todo', 'mulher', 23),
  c('to de cinco meses e com muita azia', 'mulher', 29),
  c('to grávida e minhas pernas incharam demais', 'mulher', 31),
  c('to de oito meses e com dor nas costas', 'mulher', 27),
  c('to grávida e sinto o bebê mexendo menos hoje', 'mulher', 30),
  c('ganhei nenem faz duas semanas, vim fazer o teste do pezinho', 'mulher', 25, ['puerpera']),
  c('to amamentando e meu peito empedrou todo', 'mulher', 24, ['puerpera']),
  c('to de resguardo e ainda sangrando muito', 'mulher', 32, ['puerpera']),
  c('ganhei bebê e vivo chorando por qualquer coisa', 'mulher', 26, ['puerpera']),
  c('quero começar a tomar remédio pra num engravidar', 'mulher', 21),
  c('quero trocar o anticoncepcional que me dá enjoo', 'mulher', 25),
  c('quero fazer a laqueadura, já tenho quatro filhos', 'mulher', 35),
  c('vim fazer meu preventivo que ta atrasado', 'mulher', 41),
  c('quero marcar aquele exame da mama', 'mulher', 51),
  c('minha regra vem quando quer, quero saber o motivo', 'mulher', 43),
  c('to com calorão e suor de noite, deve ser a idade', 'mulher', 48),
  c('quero fazer o teste de gravidez, to com atraso', 'mulher', 22),
  c('to grávida e com um corrimento diferente', 'mulher', 28),
  c('to grávida e sentindo umas fisgadas na barriga', 'mulher', 33),
  c('to com o bico do seio ferido de dar de mamar', 'mulher', 23, ['puerpera']),
  c('quero saber sobre colocar o diu', 'mulher', 29),
  c('minha filha de quinze anos quer um método', 'mulher', 15),
  c('to grávida e com muita dor de cabeça hoje', 'mulher', 26),
  c('to no pós parto e com febre e o peito quente', 'mulher', 28, ['puerpera']),
  c('to grávida e com muita falta de ar pra andar', 'mulher', 34),
  c('to grávida e não to sentindo o bebê desde de manhã', 'mulher', 31),
  c('to de dois meses e sangrando um pouquinho', 'mulher', 27),

  // ── Administrativo, vacina, medicamento, preventivo (36) ──
  c('vim tirar meu cartão do sus', 'adm', 24),
  c('vim buscar o resultado do exame de sangue', 'adm', 42),
  c('faltei na consulta e quero outra data', 'adm', 37),
  c('preciso de um atestado pro patrão', 'adm', 28),
  c('vim pegar encaminhamento pro ortopedista', 'adm', 54),
  c('quero saber se o resultado da ultrassom chegou', 'adm', 46),
  c('preciso de uma declaração pra creche', 'adm', 30),
  c('vim atualizar meu cadastro aqui no posto', 'adm', 33),
  c('preciso de segunda via da receita que perdi', 'adm', 51),
  c('quero marcar com a ginecologista', 'adm', 32),
  c('vim tomar a vacina contra gripe desse ano', 'vacina', 67),
  c('preciso atualizar a caderneta de vacina do menino', 'vacina', 4),
  c('vim tomar a segunda dose', 'vacina', 40),
  c('me furei num prego enferrujado ontem', 'vacina', 35, [], true),
  c('quero tomar vacina da febre amarela que vou viajar', 'vacina', 28),
  c('a vacina do meu bebê ta atrasada', 'vacina', 1, ['crianca_menor_2']),
  c('vim tomar o reforço', 'vacina', 44),
  c('dá pra tomar os dois remédio no mesmo horário', 'medic', 59, ['hipertensao']),
  c('de quanto em quanto tempo tomo esse antibiótico', 'medic', 31),
  c('pulei a dose de ontem, faço o quê agora', 'medic', 53, ['diabetes']),
  c('esse remédio dá sono, posso tomar de dia', 'medic', 39),
  c('o remédio ta me dando muito enjoo', 'medic', 36),
  c('posso beber cerveja tomando esse remédio', 'medic', 27),
  c('já to bom, posso largar o remédio da pressão', 'medic', 57, ['hipertensao']),
  c('vim fazer o preventivo de rotina', 'prev', 34),
  c('quero fazer o exame da próstata', 'prev', 55),
  c('vim medir a pressão e me pesar', 'prev', 43),
  c('quero fazer o teste de hiv', 'prev', 30),
  c('vim fazer o teste de sífilis', 'prev', 26),
  c('quero começar a caminhar e ver se posso', 'prev', 47),
  c('preciso do exame pra tirar a carteira de motorista', 'adm', 25),
  c('vim buscar a guia pra fazer o ultrassom', 'adm', 41),
  c('quando é a campanha de vacinação aqui', 'vacina', 49),
  c('vim fazer o curativo da ferida da perna', 'adm', 62, ['diabetes']),
  c('vim pegar preservativo', 'prev', 23),
  c('quero saber se posso doar sangue', 'prev', 29),

  // ── Oftalmo e odonto (22) ──
  c('meu olho ta vermelho e remelando de manhã', 'oftalmo', 29),
  c('to com a pálpebra inchada e dolorida', 'oftalmo', 25),
  c('minha vista ta embaçando pra ler de perto', 'oftalmo', 47),
  c('preciso de óculos, num enxergo de longe', 'oftalmo', 39),
  c('meus olhos coçam demais nessa poeira', 'oftalmo', 32),
  c('parece que tem cisco no meu olho o tempo todo', 'oftalmo', 36),
  c('meu olho lacrimeja sem parar com o vento', 'oftalmo', 51),
  c('to vendo umas moscas voando na vista', 'oftalmo', 54),
  c('meu filho aperta os olhos pra ver a televisão', 'oftalmo', 7),
  c('entrou areia no meu olho na praia', 'oftalmo', 33, [], true),
  c('to com dor de dente que lateja de noite', 'odonto', 33),
  c('meu siso ta nascendo e doendo demais', 'odonto', 22),
  c('quebrei um pedaço do dente comendo castanha', 'odonto', 40, [], true),
  c('minha gengiva ta inchada e sangrando', 'odonto', 37),
  c('to com um dente mole e cariado', 'odonto', 46),
  c('preciso fazer limpeza nos dentes', 'odonto', 29),
  c('meu filho ta com o dente da frente escurecido', 'odonto', 6),
  c('minha boca ta cheia de tártaro', 'odonto', 43),
  c('meu dente dói quando tomo coisa gelada', 'odonto', 34),
  c('tenho um dente podre que precisa tirar', 'odonto', 51),
  c('meu aparelho machucou a bochecha', 'odonto', 18),
  c('minha dentadura ta machucando a gengiva', 'odonto', 68),

  // ── Diversos comuns (16) ──
  c('to me sentindo muito cansada ultimamente', 'diverso', 41),
  c('vivo com sono mesmo dormindo a noite toda', 'diverso', 37),
  c('to com dor de cabeça quase todo dia', 'diverso', 35),
  c('sinto uma tontura de leve de vez em quando', 'diverso', 49),
  c('minhas mãos tremem um pouquinho', 'diverso', 60),
  c('to suando frio de noite sem motivo', 'diverso', 44),
  c('emagreci e num sei por quê', 'diverso', 53),
  c('to com o corpo todo dolorido e sem energia', 'diverso', 39),
  c('vivo com a boca seca bebendo água', 'diverso', 46, ['diabetes']),
  c('meu cabelo ta caindo muito', 'diverso', 38),
  c('to com o coração acelerado quando subo escada', 'diverso', 51, ['hipertensao']),
  c('to inchada, parece que to retendo líquido', 'diverso', 43),
  c('to sem fome faz umas semanas', 'diverso', 48),
  c('sinto um zumbido junto com tontura', 'diverso', 57),
  c('to com a vista cansada de trabalhar no computador', 'diverso', 31),
  c('to com um mal estar depois que tomei sol na obra', 'diverso', 34, [], true),

  // ══════════════════════════ AGUDO / LIMITE ══════════════════════════
  // ── Urgências (32) ──
  c('to com uma dor braba na barriga do lado direito', 'urg', 27),
  c('minha crise de asma num passou nem com a bombinha', 'urg', 34, ['asma_dpoc'], true),
  c('num consigo parar de vomitar e to fraco', 'urg', 40, [], true),
  c('to com febre alta faz três dias e o corpo doendo', 'urg', 32),
  c('minha ferida no pé ta com pus e vermelha em volta', 'urg', 65, ['diabetes']),
  c('num consigo fazer xixi desde ontem e a barriga doeu', 'urg', 71),
  c('to com uma dor nos rins que corre pra frente', 'urg', 43),
  c('minha cara inchou do lado do dente inflamado', 'urg', 36),
  c('to com muita falta de ar pra andar hoje', 'urg', 67, ['cardiopatia']),
  c('minha pressão subiu e to com dor de cabeça forte', 'urg', 58, ['hipertensao']),
  c('to com o saco inchado e doendo desde de madrugada', 'urg', 20, [], true),
  c('cortei a mão na faca de peixe e ta sangrando', 'urg', 38, [], true),
  c('meu filho ta com febre que num baixa nem com remédio', 'urg', 3, [], true),
  c('to com uma dor de cabeça diferente e vomitei', 'urg', 45),
  c('minha mãe diabética ta com o açúcar em quinhentos e vomitando', 'urg', 59, ['diabetes']),
  c('to com muita tontura e tudo rodando', 'urg', 54),
  c('to com uma íngua na virilha que atrapalha de andar', 'urg', 42),
  c('meu filho engoliu uma pilha do controle', 'urg', 3, ['crianca_menor_2'], true),
  c('to com dor no peito quando faço esforço na obra', 'urg', 57, ['hipertensao']),
  c('minha barriga ta dura e num sai nem cocô nem pum', 'urg', 61),
  c('to com sangue no xixi e ardendo', 'urg', 50),
  c('meu bebê de dois meses ta com febre', 'urg', 0, ['crianca_menor_2'], true),
  c('to com uma reação na pele depois do antibiótico', 'urg', 33, [], true),
  c('a criança ta muito molinha e num quer mamar', 'urg', 1, ['crianca_menor_2']),
  c('to com febre e ardência pra urinar e dor nas costas', 'urg', 37),
  c('painho ta confuso e com febre desde hoje cedo', 'urg', 77, [], true),
  c('to com uma queimadura na mão que empolou', 'urg', 28, [], true),
  c('minha vista embaçou de um lado e num volta', 'urg', 62, ['hipertensao'], true),
  c('to com uma dor de cabeça forte que veio de repente', 'urg', 46, [], true),
  c('minha filha ta com falta de ar e o peito afundando', 'urg', 2, ['crianca_menor_2'], true),
  c('to com o pé inchado, quente e vermelho, e febre', 'urg', 63, ['diabetes']),
  c('meu marido ta com o testículo inchado e com dor', 'urg', 24, [], true),

  // ── Emergências (26) ──
  c('meu marido ta com uma dor no peito e suando frio', 'emerg', 59, ['hipertensao'], true),
  c('mainha ficou com a boca torta e num fala direito', 'emerg', 71, [], true),
  c('painho desmaiou e num ta acordando', 'emerg', 73, [], true),
  c('to sem conseguir respirar, o peito fecha', 'emerg', 54, ['asma_dpoc'], true),
  c('meu filho ta roxo e mole, num responde', 'emerg', 2, ['crianca_menor_2'], true),
  c('minha esposa desmaiou e ta se tremendo todo', 'emerg', 44, [], true),
  c('tomei um monte de comprimido, num aguento mais viver', 'emerg', 32, [], true),
  c('to botando sangue pela boca', 'emerg', 51, [], true),
  c('minha vó caiu, bateu a cabeça e vomitou', 'emerg', 79, [], true),
  c('meu vizinho se cortou e o sangue num para de jorrar', 'emerg', 39, [], true),
  c('minha filha comeu amendoim e a boca ta inchando', 'emerg', 6, [], true),
  c('to com febre, pescoço duro e umas manchas roxas', 'emerg', 29, [], true),
  c('meu marido levou choque consertando o chuveiro', 'emerg', 43, [], true),
  c('mainha ta muito confusa, com febre e respirando rápido', 'emerg', 78, [], true),
  c('meu filho caiu do telhado e o braço ta torto', 'emerg', 13, [], true),
  c('bateu de moto ali na esquina e o osso ta pra fora', 'emerg', 26, [], true),
  c('minha irmã grávida ta sangrando muito', 'emerg', 28, [], true),
  c('to com uma dor no peito que espalha pro braço', 'emerg', 56, ['hipertensao', 'diabetes'], true),
  c('meu bebê engasgou e num consegue nem chorar', 'emerg', 0, ['crianca_menor_2'], true),
  c('minha mãe diabética ta desacordada e suando', 'emerg', 62, ['diabetes'], true),
  c('painho parou de responder e a respiração ta estranha', 'emerg', 70, ['cardiopatia'], true),
  c('a criança se tremeu todo e num voltou direito', 'emerg', 4, [], true),
  c('caiu água sanitária no olho da minha filha', 'emerg', 5, [], true),
  c('meu esposo ficou com metade do corpo dormente de repente', 'emerg', 65, ['hipertensao'], true),
  c('minha filha se cortou fundo no braço de propósito', 'emerg', 16, [], true),
  c('meu pai se afogou no mar e tossiu muita água', 'emerg', 48, [], true),

  // ── Arbovirose (14) ──
  c('to com febre e o corpo todo quebrado faz dois dias', 'arbo', 31),
  c('acho que é dengue, to com dor atrás dos olhos', 'arbo', 27),
  c('febre com as juntas doendo e manchas pelo corpo', 'arbo', 43),
  c('minha febre baixou mas agora to com dor forte na barriga', 'arbo', 35),
  c('to com dengue e apareceu sangramento na gengiva', 'arbo', 39),
  c('febre faz quatro dias e agora num paro de vomitar', 'arbo', 32),
  c('meu filho ta com febre e cheio de manchinha', 'arbo', 6),
  c('minhas juntas doem tanto que num ando, deve ser chikungunya', 'arbo', 50),
  c('febre com dor de cabeça e o corpo moído', 'arbo', 28),
  c('depois que a febre cedeu me deu fraqueza e tontura', 'arbo', 37),
  c('to com febre e uma fraqueza danada, suspeito de dengue', 'arbo', 44),
  c('minha filha ta com febre e agora reclamando da barriga', 'arbo', 8),
  c('to com febre e umas pintinhas vermelhas no braço', 'arbo', 25),
  c('teve dengue na minha rua toda e agora to com febre', 'arbo', 33),

  // ── Violência e crise mental grave (11) ──
  c('meu marido me bateu e to com medo de voltar pra casa', 'violencia', 33),
  c('fui forçada por um homem ontem de noite', 'violencia', 21, [], true),
  c('minha vizinha vive batendo nos meninos dela', 'violencia', 5),
  c('painho ta sendo maltratado pela cuidadora', 'violencia', 81),
  c('tive relação sem camisinha e to com medo de pegar hiv', 'violencia', 26, [], true),
  c('meu namorado me ameaça e num me deixa sair de casa', 'violencia', 24),
  c('to ouvindo umas vozes mandando eu fazer coisa ruim', 'mentalgrave', 30),
  c('meu irmão surtou, ta agressivo e falando coisa sem sentido', 'mentalgrave', 27),
  c('parei de beber faz três dias e to tremendo e vendo vulto', 'mentalgrave', 46),
  c('to com vontade de me matar e já pensei como', 'mentalgrave', 38),
  c('meu filho apanhou do padrasto e ta com marca no braço', 'violencia', 9),

  // ── Vago e ruído (19) ──
  c('to passando mal, num sei explicar direito', 'vago', 43),
  c('num to bom não, doutor', 'vago', 65),
  c('to me sentindo esquisita, sei lá', 'vago', 37),
  c('to ruim das ideia', 'vago', 54),
  c('sinto um negócio estranho por dentro', 'vago', 48),
  c('num to legal, to meio adoentada', 'vago', 57),
  c('me deu uma indisposição cedo da manhã', 'vago', 61),
  c('to meio zonzo e sem jeito', 'vago', 50),
  c('num sei o que eu tenho, só sei que to mal', 'vago', 33),
  c('minha filha ta diferente, meio quieta', 'vago', 11),
  c('vim ver o que pode ser isso que eu sinto', 'vago', 46),
  c('to esmorecida, sem eito pra nada', 'vago', 59),
  c('to com uma coisa ruim no estômago faiz dias', 'ruido', 39),
  c('minha cabesa doi de mais', 'ruido', 32),
  c('to com febri e o corpu todo doendo', 'ruido', 28),
  c('num to conseguino respira bem', 'ruido', 59, ['asma_dpoc']),
  c('minha preção ta muinto auta', 'ruido', 57, ['hipertensao']),
  c('meu minino ta com febri auta e molinho', 'ruido', 3),
  c('ta doendo meu peito e to suano frio', 'ruido', 55, ['hipertensao'], true),
];
