/**
 * Segundo lote sintético — 400 relatos, todos distintos entre si e do lote de 315.
 *
 * Escritos em linguagem popular, como a pessoa fala na recepção de UBS, USF e UPA. A maior
 * parte (~300) é demanda comum de Atenção Básica; o restante são urgências, emergências e
 * casos-limite. Escrito DELIBERADAMENTE sem consultar o catálogo de critérios — a auditoria só
 * vale se medir o que o sistema não sabe, não o que já sabe.
 *
 *   npm run auditar -- testes/lote-sintetico-400.ts
 */

export interface Caso {
  relato: string;
  idade?: number;
  agravantes?: string[];
  inicioMenos24h?: boolean;
  paraQuem?: 'proprio' | 'terceiro';
  grupo: string;
}

const c = (
  relato: string,
  grupo: string,
  idade?: number,
  agravantes: string[] = [],
  inicioMenos24h = false,
): Caso => ({ relato, grupo, idade, agravantes, inicioMenos24h });

export const LOTE: Caso[] = [
  // ═══════════════════════════ COMUM ═══════════════════════════
  // ── Respiratório leve e ORL (40) ──
  c('tô todo entupido do nariz e espirrando', 'resp', 29, [], true),
  c('peguei um resfriado forte, tô com o corpo mole', 'resp', 34),
  c('minha garganta tá raspando desde ontem', 'resp', 22, [], true),
  c('dói pra engolir e tô com uma febrinha', 'resp', 26),
  c('essa tosse seca não me deixa dormir', 'resp', 45),
  c('tô com uma tosse cheia de catarro verde', 'resp', 51),
  c('meu nariz vive tampado de manhã cedo', 'resp', 38),
  c('acho que é sinusite, dói a testa toda', 'resp', 42),
  c('fiquei rouco de tanto falar no trabalho', 'resp', 36),
  c('minha nenê tá gripadinha e tossindo à noite', 'resp', 3),
  c('o menino pegou catarro na creche', 'resp', 4),
  c('meu ouvido tampou depois da gripe', 'resp', 31),
  c('acordei com o ouvido latejando', 'resp', 19, [], true),
  c('meu ouvido tá zunindo faz dias', 'resp', 57),
  c('espirro sem parar quando acordo, é alergia', 'resp', 33),
  c('minha rinite atacou com essa poeira', 'resp', 40),
  c('tô com catarro amarelo faz uns quatro dias', 'resp', 48),
  c('garganta inflamada e uma íngua no pescoço', 'resp', 27),
  c('minha voz sumiu quase toda', 'resp', 44),
  c('peguei friagem na chuva e tô toda dolorida', 'resp', 52),
  c('meu filho vive gripado, tá espirrando de novo', 'resp', 6),
  c('tô com o peito congestionado e tossindo', 'resp', 39),
  c('coriza que não para faz uma semana', 'resp', 30),
  c('dor de garganta que vai e volta', 'resp', 24),
  c('acho que tô com amigdalite, garganta cheia de pus', 'resp', 21),
  c('meu nariz sangra quando assoa forte', 'orl', 35),
  c('sinto o ouvido cheio de cera', 'orl', 60),
  c('não tô escutando bem desse ouvido', 'orl', 66),
  c('meu filho puxa muito o ronco pra dormir', 'orl', 5),
  c('tô com aftas na boca faz dias', 'orl', 28),
  c('apareceu uma bolha no céu da boca', 'orl', 41),
  c('minha gengiva tá sangrando quando escovo', 'orl', 37),
  c('tô com mau hálito e não sei por quê', 'orl', 45),
  c('sinto um gosto ruim na boca o tempo todo', 'orl', 53),
  c('minha língua tá esbranquiçada', 'orl', 32),
  c('tô com o nariz ardendo por dentro', 'resp', 25),
  c('meu peito chia de leve quando deito', 'resp', 58, ['asma_dpoc']),
  c('preciso renovar a bombinha da asma', 'resp', 34, ['asma_dpoc']),
  c('meu bebê tá com o nariz rancho e não mama direito', 'resp', 1, ['crianca_menor_2']),
  c('tô gripada mas preciso trabalhar, quero um remédio', 'resp', 29),

  // ── Musculoesquelético e trauma leve (35) ──
  c('minha coluna tá me matando faz uma semana', 'musculo', 47),
  c('travei o pescoço, acordei sem conseguir virar', 'musculo', 38, [], true),
  c('dor no fundo das costas que desce pra perna', 'musculo', 55),
  c('meu joelho tá inchado e rangendo', 'musculo', 61),
  c('não consigo levantar o braço de dor no ombro', 'musculo', 50),
  c('torci o tornozelo descendo a escada', 'musculo', 33, [], true),
  c('meu punho dói de mexer no computador o dia todo', 'musculo', 29),
  c('tô com uma dor nas cadeiras que não passa', 'musculo', 64),
  c('minhas juntas dos dedos amanhecem duras', 'musculo', 58),
  c('dor no calcanhar quando piso ao acordar', 'musculo', 46),
  c('tô com câimbra na batata da perna toda noite', 'musculo', 53),
  c('caí no banheiro e ralei o cotovelo', 'trauma', 72, [], true),
  c('bati a canela na quina da cama e inchou', 'trauma', 34, [], true),
  c('meu filho caiu da bicicleta e esfolou o joelho', 'trauma', 11, [], true),
  c('prensei o dedo na porta do carro', 'trauma', 40, [], true),
  c('minha lombar trava quando carrego peso', 'musculo', 49),
  c('dor no meio das costas de tanto ficar sentado', 'musculo', 42),
  c('meus dedos formigam de noite, acordo dormente', 'musculo', 51),
  c('sinto uma fisgada na coluna quando me abaixo', 'musculo', 44),
  c('minha perna incha no fim do dia', 'musculo', 62, ['hipertensao']),
  c('varizes na perna doendo muito', 'musculo', 57),
  c('meu pé formiga o tempo todo', 'musculo', 65, ['diabetes']),
  c('torci o dedão jogando bola no fim de semana', 'trauma', 23, [], true),
  c('bati a cabeça leve na porta do armário, sem tontura', 'trauma', 36, [], true),
  c('meu ombro estala quando levanto peso', 'musculo', 39),
  c('dor na sola do pé de andar o dia inteiro', 'musculo', 48),
  c('minha mão tá inchada de manhã', 'musculo', 55),
  c('dor no quadril quando subo escada', 'musculo', 68),
  c('tô com bursite no ombro, o médico já falou', 'musculo', 60),
  c('meu joelho falseia quando ando muito', 'musculo', 54),
  c('dor no cóccix depois que sentei no chão duro', 'trauma', 31),
  c('estirei o músculo da coxa correndo', 'musculo', 28, [], true),
  c('meu braço tá roxo onde tomei a injeção', 'trauma', 43),
  c('caí sentada e tô com dor na bunda', 'trauma', 59, [], true),
  c('dor nas costas que piora quando respiro fundo', 'musculo', 37),

  // ── Dermatologia (30) ──
  c('apareceu uma coceira no corpo que não passa', 'derm', 34),
  c('tô cheia de brotoeja com esse calor', 'derm', 27),
  c('meu filho tá com uma alergia vermelha na pele', 'derm', 5),
  c('apareceu uma micose no meio dos dedos do pé', 'derm', 41),
  c('tô com uma verruga na sola do pé que dói', 'derm', 36),
  c('minha unha do dedão encravou e inflamou', 'derm', 45),
  c('apareceu uma mancha escura no rosto', 'derm', 52),
  c('tô com caspa e coceira no couro cabeludo', 'derm', 38),
  c('minha pele descama e coça nas dobras', 'derm', 49),
  c('apareceu um caroço debaixo do braço', 'derm', 33),
  c('tenho uma pinta que tá crescendo nas costas', 'derm', 58),
  c('minha filha tá com assadura forte na fralda', 'derm', 1, ['crianca_menor_2']),
  c('fui picado por um mosquito e inchou tudo', 'derm', 29, [], true),
  c('apareceu uma frieira que descasca entre os dedos', 'derm', 44),
  c('tô com espinha demais no rosto e nas costas', 'derm', 18),
  c('minha pele tá amarelada, será que é do fígado', 'derm', 47),
  c('apareceu uma bolha de água na mão do nada', 'derm', 35),
  c('tô com uma coceira danada na virilha', 'derm', 39),
  c('meu bebê tá com a pele ressecada e vermelha', 'derm', 0, ['crianca_menor_2']),
  c('apareceu uma placa vermelha e áspera no braço', 'derm', 42),
  c('minha ferida antiga voltou a coçar e inflamar', 'derm', 50),
  c('tô com furúnculo na coxa cheio de pus', 'derm', 37),
  c('apareceu um cobreiro nas costas ardendo muito', 'derm', 55),
  c('minha pele tá cheia de manchas brancas', 'derm', 31),
  c('tô com uma queimadura de sol que empolou', 'derm', 26, [], true),
  c('minhas mãos rachadas e sangrando de tanto lavar', 'derm', 48),
  c('apareceu uma verruguinha no pescoço', 'derm', 40),
  c('tô com o pé de atleta descascando', 'derm', 33),
  c('minha filha tá cheia de bolinhas de catapora', 'derm', 6),
  c('apareceu um sinal novo e coçando na perna', 'derm', 45),

  // ── Gastrointestinal (35) ──
  c('tô com azia toda vez que como fritura', 'gastro', 43),
  c('sinto queimação no estômago à noite', 'gastro', 51),
  c('minha gastrite atacou de novo com o nervoso', 'gastro', 38),
  c('tô com o estômago embrulhado desde ontem', 'gastro', 30, [], true),
  c('diarreia que não para desde de manhã', 'gastro', 27, [], true),
  c('tô com prisão de ventre faz cinco dias', 'gastro', 60),
  c('meu filho tá com diarreia e uma febrinha', 'gastro', 4, [], true),
  c('sinto muito gás e a barriga estufada', 'gastro', 44),
  c('vomitei o café da manhã e passou', 'gastro', 33, [], true),
  c('tô enjoada, acho que comi algo estragado', 'gastro', 29, [], true),
  c('dor de barriga fraca que vai e vem', 'gastro', 35),
  c('cólica no fundo da barriga desde ontem', 'gastro', 41, [], true),
  c('tô com hemorroida e sangra quando evacuo', 'gastro', 47),
  c('sai um sanguinho vivo no papel quando limpo', 'gastro', 39),
  c('meu intestino tá preso e a barriga dura', 'gastro', 55),
  c('tô com soluço que não para faz horas', 'gastro', 32),
  c('sinto o estômago queimando quando fico com fome', 'gastro', 46),
  c('meu filho reclama de dor de barriga toda manhã', 'gastro', 8),
  c('tô com refluxo, a comida volta na garganta', 'gastro', 50),
  c('diarreia e cólica depois que comi na rua', 'gastro', 28, [], true),
  c('minha barriga ronca e tá solta faz dias', 'gastro', 36),
  c('perdi o apetite e tô emagrecendo sem querer', 'gastro', 58),
  c('tô com ânsia de vômito mas não sai nada', 'gastro', 34),
  c('meu bebê golfa muito depois de mamar', 'gastro', 0, ['crianca_menor_2']),
  c('tô com uma dor em cima da barriga que aperta', 'gastro', 49),
  c('sinto o intestino preso e dor pra evacuar', 'gastro', 62),
  c('tô com verme, sinto coceira no ânus à noite', 'gastro', 12),
  c('minha filha range os dentes e tá com verme', 'gastro', 7),
  c('comi demais na festa e tô passando mal do estômago', 'gastro', 40, [], true),
  c('tô com gastura e vontade de vomitar', 'gastro', 31),
  c('minha digestão tá lenta e me sinto empanturrada', 'gastro', 53),
  c('tô com diarreia amarela e fraqueza', 'gastro', 44),
  c('dor de barriga e febre baixa faz dois dias', 'gastro', 26),
  c('meu estômago dói quando tomo o remédio de jejum', 'gastro', 57),
  c('tô com prisão de ventre desde que mudei de cidade', 'gastro', 38),

  // ── Urinário e genital (25) ──
  c('tô com ardência quando faço xixi', 'urin', 26),
  c('tô indo no banheiro toda hora fazer xixi', 'urin', 33),
  c('minha urina tá turva e com cheiro forte', 'urin', 48),
  c('acho que peguei infecção de urina de novo', 'urin', 39),
  c('tô urinando pouquinho e ardendo', 'urin', 44),
  c('meu marido reclama que levanta muito pra urinar', 'urin', 66),
  c('tô com dor no pé da barriga e vontade de urinar', 'urin', 35),
  c('minha filha faz xixi na cama de novo aos 8 anos', 'urin', 8),
  c('tô com um corrimento esbranquiçado e coceira', 'genital', 28),
  c('minha menstruação desceu muito forte esse mês', 'genital', 43),
  c('faz três meses que não menstruo e não tô grávida', 'genital', 46),
  c('tô com coceira na parte íntima', 'genital', 31),
  c('apareceu uma ferida na região íntima', 'genital', 24),
  c('sinto dor na relação com meu marido', 'genital', 37),
  c('tô com um corrimento amarelo e mau cheiro', 'genital', 29),
  c('meu marido tá com ardência pra urinar e corrimento', 'genital', 34),
  c('minha menstruação tá irregular esse ano todo', 'genital', 41),
  c('tô com cólica menstrual muito forte', 'genital', 22),
  c('apareceu uma verruga na parte íntima', 'genital', 27),
  c('minha bexiga parece que não esvazia', 'urin', 59),
  c('tô com vontade de urinar mas sai pouco', 'urin', 51),
  c('sinto um peso embaixo, acho que é a bexiga', 'urin', 55),
  c('tô grávida e com ardência pra fazer xixi', 'genital', 25),
  c('meu filho reclama que arde pra fazer xixi', 'urin', 6),
  c('tô com um caroço dolorido na virilha', 'genital', 38),

  // ── Saúde mental leve (25) ──
  c('ando muito ansiosa e sem paciência', 'mental', 34),
  c('não consigo dormir de tanta preocupação', 'mental', 42),
  c('tô numa tristeza que não passa', 'mental', 38),
  c('preciso muito conversar com um psicólogo', 'mental', 29),
  c('tô estressado e explodindo com todo mundo', 'mental', 45),
  c('meu coração dispara quando fico nervosa', 'mental', 31),
  c('acho que tô com depressão, sem vontade de nada', 'mental', 40),
  c('acabou meu remédio da ansiedade', 'mental', 47),
  c('tô com a cabeça cheia e não relaxo', 'mental', 36),
  c('durmo demais e mesmo assim vivo cansada', 'mental', 33),
  c('tô comendo demais por ansiedade', 'mental', 28),
  c('meu filho adolescente tá muito isolado e triste', 'mental', 15),
  c('não tenho ânimo pra levantar da cama', 'mental', 44),
  c('tô chorando à toa esses dias', 'mental', 39),
  c('vivo esquecido das coisas e preocupado com isso', 'mental', 62),
  c('tô bebendo demais e queria uma ajuda pra parar', 'mental', 50),
  c('meu marido tá bebendo muito e a família não aguenta', 'mental', 48),
  c('tô com crise de ansiedade e falta de ar', 'mental', 30),
  c('sinto um aperto no peito quando fico nervoso', 'mental', 35),
  c('não consigo me concentrar em nada ultimamente', 'mental', 27),
  c('tô com insônia e acordo cansada', 'mental', 41),
  c('perdi meu emprego e tô muito pra baixo', 'mental', 37),
  c('sinto medo de sair de casa sozinha', 'mental', 33),
  c('minha filha tá se cortando e não sei o que fazer', 'mental', 16),
  c('tô com pensamento ruim mas nunca faria nada', 'mental', 43),

  // ── Pediatria comum (30) ──
  c('meu filho tá com febre desde a madrugada', 'ped', 3, [], true),
  c('a nenê tá quentinha e chorosa', 'ped', 1, ['crianca_menor_2'], true),
  c('meu menino tá com tosse e chiado no peito', 'ped', 5),
  c('minha filha vomitou umas três vezes hoje', 'ped', 6, [], true),
  c('o bebê tá com diarreia e a bunda assada', 'ped', 1, ['crianca_menor_2']),
  c('meu filho não quis o almoço e tá manhoso', 'ped', 4),
  c('a criança tá com o olho vermelho e grudando', 'ped', 5),
  c('meu filho tá com dor de ouvido e chorando', 'ped', 3),
  c('a menina tá com piolho de novo da escola', 'ped', 8),
  c('meu bebê tá com sapinho na boca', 'ped', 0, ['crianca_menor_2']),
  c('minha filha tá com uma tosse de cachorro', 'ped', 2, ['crianca_menor_2']),
  c('o nenê nasceu semana passada, vim pra consulta', 'ped', 0, ['crianca_menor_2']),
  c('meu filho tá com manchinhas vermelhas e febre', 'ped', 4),
  c('a criança tá comendo mal e não ganha peso', 'ped', 1, ['crianca_menor_2']),
  c('meu bebê chora muito de cólica à noite', 'ped', 0, ['crianca_menor_2']),
  c('meu filho engasgou com leite mas tá respirando bem', 'ped', 0, ['crianca_menor_2']),
  c('a menina tá com dor de barriga e sem fazer cocô', 'ped', 7),
  c('meu filho tá arranhando muito a cabeça', 'ped', 6),
  c('vim vacinar meu bebê que tá na idade', 'ped', 0, ['crianca_menor_2']),
  c('a criança tá com catarro e ronco pra respirar', 'ped', 2, ['crianca_menor_2']),
  c('meu filho caiu e bateu o queixo, tá chorando', 'ped', 3, [], true),
  c('minha filha reclama de dor nas perninhas à noite', 'ped', 5),
  c('o bebê tá com o umbigo vermelho e cheiroso', 'ped', 0, ['crianca_menor_2']),
  c('meu filho tá com febre e puxando a orelha', 'ped', 1, ['crianca_menor_2']),
  c('a nenê tá com aftas e não quer mamar', 'ped', 1, ['crianca_menor_2']),
  c('meu menino molha a cama e já tem 9 anos', 'ped', 9),
  c('minha filha tá com verruga na mão', 'ped', 7),
  c('o bebê tá com os olhinhos lacrimejando', 'ped', 0, ['crianca_menor_2']),
  c('meu filho tá gaguejando e a professora comentou', 'ped', 5),
  c('a criança comeu terra e tô preocupada com verme', 'ped', 3),

  // ── Crônicos e idoso (35) ──
  c('vim renovar a receita do remédio de pressão', 'cronico', 62, ['hipertensao']),
  c('acabou meu remédio de diabetes', 'cronico', 58, ['diabetes']),
  c('minha pressão deu 15 por 9 na farmácia', 'cronico', 60, ['hipertensao']),
  c('medi a pressão em casa e tava 17 por 10', 'cronico', 64, ['hipertensao']),
  c('meu açúcar amanheceu em 300', 'cronico', 55, ['diabetes']),
  c('tô com muita sede e urinando demais', 'cronico', 49, ['diabetes']),
  c('vim pra consulta de rotina do diabetes', 'cronico', 61, ['diabetes']),
  c('quero saber meu resultado de colesterol', 'cronico', 53),
  c('meu médico pediu pra acompanhar a tireoide', 'cronico', 44),
  c('tô tomando remédio de pressão mas me sinto tonto', 'cronico', 67, ['hipertensao']),
  c('minha diabetes tá descontrolada esse mês', 'cronico', 59, ['diabetes']),
  c('preciso pegar a insulina na farmácia da unidade', 'cronico', 57, ['diabetes']),
  c('vim buscar as tiras de medir a glicose', 'cronico', 63, ['diabetes']),
  c('minha avó de 82 anos tá comendo pouco e fraca', 'idoso', 82),
  c('meu pai idoso tá mais esquecido e confuso às vezes', 'idoso', 79),
  c('minha mãe de 75 caiu no quintal ontem', 'idoso', 75, [], true),
  c('meu sogro acamado tá com uma ferida no bumbum', 'idoso', 84, ['acamado']),
  c('minha vó não tá dormindo à noite e agitada', 'idoso', 80),
  c('meu pai toma dez remédios e vive tonto', 'idoso', 77, ['hipertensao', 'diabetes']),
  c('minha mãe idosa tá com a perna inchada de um lado', 'idoso', 78),
  c('meu avô tá com falta de ar quando anda pouco', 'idoso', 81, ['cardiopatia']),
  c('minha sogra tá esquecendo de tomar os remédios', 'idoso', 76),
  c('meu pai reclama que tá enxergando embaçado', 'idoso', 70, ['diabetes']),
  c('minha avó tá com tontura quando levanta da cama', 'idoso', 83),
  c('meu tio tá amarelo dos olhos e da pele', 'cronico', 58),
  c('tô com o colesterol e o triglicerídeo alto no exame', 'cronico', 46),
  c('minha pressão vive subindo quando fico nervosa', 'cronico', 51, ['hipertensao']),
  c('vim medir a pressão que tô com dor na nuca', 'cronico', 59, ['hipertensao']),
  c('meu marido diabético tá com uma ferida no pé', 'cronico', 65, ['diabetes']),
  c('tô com formigamento nos pés por causa da diabetes', 'cronico', 62, ['diabetes']),
  c('minha mãe idosa não quer comer nem beber água', 'idoso', 85),
  c('meu pai tá urinando pouco e as pernas incharam', 'idoso', 74, ['hipertensao']),
  c('minha avó reclama que o coração dispara às vezes', 'idoso', 79, ['cardiopatia']),
  c('tô com a pressão baixa e me sinto fraco', 'cronico', 48),
  c('meu remédio de pressão acabou e minha cabeça dói', 'cronico', 56, ['hipertensao']),

  // ── Mulher: gestação, puerpério, planejamento (25) ──
  c('descobri que tô grávida e quero começar o pré-natal', 'mulher', 27),
  c('tô grávida de uns três meses e enjoando muito', 'mulher', 24),
  c('tô de cinco meses e com muita azia', 'mulher', 30),
  c('tô grávida e minhas pernas incharam', 'mulher', 32),
  c('tô de oito meses e com dor nas costas', 'mulher', 28),
  c('tô grávida e sinto o bebê mexendo menos hoje', 'mulher', 29),
  c('ganhei neném faz duas semanas e vim fazer o teste do pezinho', 'mulher', 26, ['puerpera']),
  c('tô amamentando e meu peito empedrou', 'mulher', 25, ['puerpera']),
  c('tô de resguardo e ainda sangrando bastante', 'mulher', 31, ['puerpera']),
  c('ganhei bebê e tô muito triste e chorosa', 'mulher', 27, ['puerpera']),
  c('quero começar a tomar anticoncepcional', 'mulher', 22),
  c('quero trocar meu anticoncepcional que me dá enjoo', 'mulher', 26),
  c('quero fazer laqueadura, já tenho três filhos', 'mulher', 34),
  c('vim fazer meu preventivo que tá atrasado', 'mulher', 40),
  c('preciso marcar a mamografia, tenho 52 anos', 'mulher', 52),
  c('minha menstruação some e volta, quero investigar', 'mulher', 44),
  c('tô com fogacho e suor, acho que é a menopausa', 'mulher', 49),
  c('quero fazer o teste de gravidez, tô com atraso', 'mulher', 23),
  c('tô grávida e com um corrimento diferente', 'mulher', 28),
  c('tô grávida e sentindo umas contrações fracas', 'mulher', 33),
  c('meu bico do peito rachou de amamentar', 'mulher', 24, ['puerpera']),
  c('quero saber sobre o DIU', 'mulher', 30),
  c('minha filha de 15 anos quer método contraceptivo', 'mulher', 15),
  c('tô grávida e com muita dor de cabeça hoje', 'mulher', 27),
  c('tô no pós-parto e com febre e o peito quente', 'mulher', 29, ['puerpera']),

  // ── Administrativo, vacina, medicamento, preventivo (35) ──
  c('preciso fazer o cartão do SUS', 'adm', 25),
  c('vim buscar o resultado do meu exame de sangue', 'adm', 43),
  c('quero remarcar a consulta que perdi', 'adm', 38),
  c('preciso de um atestado de comparecimento', 'adm', 29),
  c('vim pegar o encaminhamento pro ortopedista', 'adm', 55),
  c('quero saber se meu exame de imagem já chegou', 'adm', 47),
  c('preciso da declaração pra creche do meu filho', 'adm', 31),
  c('vim atualizar meu cadastro na unidade', 'adm', 34),
  c('preciso de uma segunda via da receita', 'adm', 52),
  c('quero agendar consulta com a ginecologista', 'adm', 33),
  c('vim tomar a vacina da gripe', 'vacina', 68),
  c('preciso atualizar a carteira de vacina do meu filho', 'vacina', 4),
  c('vim tomar a segunda dose da vacina', 'vacina', 41),
  c('me cortei ontem e preciso da vacina do tétano', 'vacina', 36, [], true),
  c('quero tomar a vacina da febre amarela pra viajar', 'vacina', 29),
  c('a vacina do meu bebê tá atrasada', 'vacina', 1, ['crianca_menor_2']),
  c('vim tomar o reforço da vacina', 'vacina', 45),
  c('posso tomar o remédio da pressão junto com o do colesterol', 'medic', 60, ['hipertensao']),
  c('esse antibiótico é de quantas em quantas horas', 'medic', 32),
  c('esqueci de tomar o remédio ontem, tomo dobrado', 'medic', 54, ['diabetes']),
  c('esse remédio pode dar sono', 'medic', 40),
  c('o remédio tá me dando muito enjoo', 'medic', 37),
  c('posso beber tomando esse antibiótico', 'medic', 28),
  c('quero saber se posso parar o remédio da pressão', 'medic', 58, ['hipertensao']),
  c('vim fazer meu preventivo de rotina', 'prev', 35),
  c('quero fazer o exame de próstata', 'prev', 56),
  c('vim medir minha pressão e meu peso', 'prev', 44),
  c('quero fazer o teste de HIV', 'prev', 31),
  c('vim fazer o teste de covid, tô com sintomas', 'prev', 39),
  c('quero começar a fazer atividade e ver se posso', 'prev', 48),
  c('preciso do exame pra carteira de motorista', 'adm', 27),
  c('vim buscar a guia pra fazer ultrassom', 'adm', 42),
  c('quero saber quando é a campanha de vacinação', 'vacina', 50),
  c('preciso trocar o curativo da minha perna', 'adm', 63, ['diabetes']),
  c('vim pegar fralda geriátrica pra minha mãe', 'adm', 58),

  // ── Oftalmo e odonto (20) ──
  c('meu olho tá vermelho e remelando de manhã', 'oftalmo', 30),
  c('apareceu um terçol no meu olho', 'oftalmo', 26),
  c('minha vista tá embaçando pra ler', 'oftalmo', 48),
  c('preciso de óculos, não enxergo de longe', 'oftalmo', 40),
  c('meu olho coça muito, deve ser alergia', 'oftalmo', 33),
  c('sinto uma areia no olho o dia todo', 'oftalmo', 37),
  c('meu olho lacrimeja sem parar', 'oftalmo', 52),
  c('tô enxergando umas moscas voando na vista', 'oftalmo', 55),
  c('meu filho tá apertando os olhos pra ver a TV', 'oftalmo', 7),
  c('tô com dor de dente que lateja à noite', 'odonto', 34),
  c('meu dente do siso tá nascendo e doendo', 'odonto', 23),
  c('quebrei um pedaço do dente comendo', 'odonto', 41, [], true),
  c('minha gengiva tá inchada e sangrando', 'odonto', 38),
  c('tô com um dente mole e cariado', 'odonto', 47),
  c('preciso fazer uma limpeza nos dentes', 'odonto', 30),
  c('meu filho tem um dente de leite mole', 'odonto', 6),
  c('minha boca tá cheia de tártaro', 'odonto', 44),
  c('sinto sensibilidade nos dentes com gelado', 'odonto', 35),
  c('preciso arrancar um dente estragado', 'odonto', 52),
  c('meu aparelho no dente machucou a bochecha', 'odonto', 19),

  // ── Diversos comuns (15) ──
  c('tô me sentindo muito cansada ultimamente', 'diverso', 42),
  c('vivo com sono o dia todo mesmo dormindo', 'diverso', 38),
  c('tô com dor de cabeça quase todo dia', 'diverso', 36),
  c('sinto uma tontura leve de vez em quando', 'diverso', 50),
  c('minhas mãos tremem de leve às vezes', 'diverso', 61),
  c('tô suando frio à noite sem motivo', 'diverso', 45),
  c('emagreci sem fazer dieta e tô preocupado', 'diverso', 54),
  c('tô com o corpo todo dolorido e sem energia', 'diverso', 40),
  c('vivo com a boca seca e bebendo água', 'diverso', 47, ['diabetes']),
  c('minhas unhas tão quebradiças e o cabelo caindo', 'diverso', 39),
  c('tô com soluços e arrotos demais', 'diverso', 33),
  c('sinto um zumbido e tontura juntos', 'diverso', 58),
  c('tô inchada e pesada, retendo líquido', 'diverso', 44),
  c('tô com falta de apetite faz semanas', 'diverso', 49),
  c('sinto o coração acelerado quando subo escada', 'diverso', 52, ['hipertensao']),

  // ═══════════════════════════ AGUDO / LIMITE ═══════════════════════════
  // ── Urgências (30) ──
  c('tô com uma dor de barriga muito forte do lado direito', 'urg', 28),
  c('minha crise de asma não passou com a bombinha', 'urg', 35, ['asma_dpoc'], true),
  c('não consigo parar de vomitar e tô fraco', 'urg', 41, [], true),
  c('tô com febre alta há três dias e dor no corpo', 'urg', 33),
  c('minha ferida no pé tá com pus e vermelha ao redor', 'urg', 66, ['diabetes']),
  c('não consigo fazer xixi desde ontem e a barriga doeu', 'urg', 72),
  c('tô com uma dor nos rins que irradia pra frente', 'urg', 44),
  c('meu rosto inchou de um lado por causa do dente', 'urg', 37),
  c('tô com muita falta de ar pra andar hoje', 'urg', 68, ['cardiopatia']),
  c('minha pressão subiu e tô com muita dor de cabeça', 'urg', 59, ['hipertensao']),
  c('tô com o testículo inchado e doendo desde de manhã', 'urg', 21, [], true),
  c('cortei a mão na faca e tá sangrando bastante', 'urg', 39, [], true),
  c('meu filho tá com febre que não baixa com remédio', 'urg', 3, [], true),
  c('tô com uma dor de cabeça diferente e vômito', 'urg', 46),
  c('minha diabética tá com o açúcar em 500 e vomitando', 'urg', 60, ['diabetes']),
  c('tô com muita tontura e o mundo rodando', 'urg', 55),
  c('apareceu um caroço na virilha que dói pra andar', 'urg', 43),
  c('meu filho engoliu um botão de pilha', 'urg', 3, ['crianca_menor_2'], true),
  c('tô com dor no peito quando faço esforço', 'urg', 58, ['hipertensao']),
  c('minha barriga tá dura e não consigo evacuar nem soltar gás', 'urg', 62),
  c('tô com sangue na urina e dor pra urinar', 'urg', 51),
  c('meu bebê de dois meses tá com febre', 'urg', 0, ['crianca_menor_2'], true),
  c('tô com uma reação na pele depois do antibiótico', 'urg', 34, [], true),
  c('a criança tá muito molinha e sem querer mamar', 'urg', 1, ['crianca_menor_2']),
  c('tô com febre e ardência pra urinar e dor nas costas', 'urg', 38),
  c('meu pai tá confuso e com febre desde hoje', 'urg', 78, [], true),
  c('tô com uma queimadura na mão que bolhou', 'urg', 29, [], true),
  c('minha vista embaçou de um lado e não volta', 'urg', 63, ['hipertensao'], true),
  c('tô com dor forte de cabeça que começou de repente', 'urg', 47, [], true),
  c('minha filha tá com falta de ar e o peito afundando', 'urg', 2, ['crianca_menor_2'], true),

  // ── Emergências (25) ──
  c('meu marido tá com dor no peito e suando frio', 'emerg', 60, ['hipertensao'], true),
  c('minha mãe ficou com a boca torta e não fala direito', 'emerg', 70, [], true),
  c('meu pai desmaiou e não tá acordando', 'emerg', 74, [], true),
  c('tô sem conseguir respirar direito, o peito fecha', 'emerg', 55, ['asma_dpoc'], true),
  c('meu filho tá roxo e mole, não responde', 'emerg', 2, ['crianca_menor_2'], true),
  c('minha esposa desmaiou e tá convulsionando', 'emerg', 45, [], true),
  c('tomei um monte de comprimido, não aguento mais viver', 'emerg', 33, [], true),
  c('tô vomitando sangue vivo', 'emerg', 52, [], true),
  c('minha avó caiu, bateu a cabeça e vomitou', 'emerg', 80, [], true),
  c('meu vizinho se cortou e o sangue não para de jorrar', 'emerg', 40, [], true),
  c('minha filha comeu amendoim e a boca tá inchando', 'emerg', 6, [], true),
  c('meu pai tá com febre, pescoço duro e manchas roxas', 'emerg', 30, [], true),
  c('meu marido levou um choque forte consertando o chuveiro', 'emerg', 44, [], true),
  c('minha mãe tá muito confusa, com febre e respirando rápido', 'emerg', 79, [], true),
  c('meu filho caiu do telhado e tá com o braço torto', 'emerg', 14, [], true),
  c('a moto bateu e o rapaz tá com o osso pra fora', 'emerg', 25, [], true),
  c('minha irmã grávida tá sangrando muito', 'emerg', 29, [], true),
  c('tô com uma dor no peito que espalha pro braço', 'emerg', 57, ['hipertensao', 'diabetes'], true),
  c('meu bebê engasgou e não consegue respirar nem chorar', 'emerg', 0, ['crianca_menor_2'], true),
  c('minha mãe diabética tá desacordada e suando', 'emerg', 63, ['diabetes'], true),
  c('meu pai parou de responder e tá com a respiração estranha', 'emerg', 71, ['cardiopatia'], true),
  c('a criança convulsionou e não voltou direito', 'emerg', 4, [], true),
  c('caiu produto de limpeza no olho da minha filha', 'emerg', 5, [], true),
  c('meu esposo tá com metade do corpo dormente de repente', 'emerg', 66, ['hipertensao'], true),
  c('minha filha adolescente se cortou fundo no braço', 'emerg', 16, [], true),

  // ── Arbovirose (12) ──
  c('tô com febre e dor no corpo todo faz dois dias', 'arbo', 32),
  c('acho que é dengue, tô com dor atrás dos olhos', 'arbo', 28),
  c('febre, dor nas juntas e umas manchas vermelhas', 'arbo', 44),
  c('minha febre baixou mas agora tô com dor forte na barriga', 'arbo', 36),
  c('tô com dengue e apareceu sangramento na gengiva', 'arbo', 40),
  c('febre há quatro dias e agora não paro de vomitar', 'arbo', 33),
  c('meu filho tá com febre e cheio de manchinhas', 'arbo', 7),
  c('tô com as juntas tão doloridas que nem ando, deve ser chikungunya', 'arbo', 51),
  c('febre com dor de cabeça e o corpo quebrado', 'arbo', 29),
  c('a febre passou e me deu uma moleza e tontura', 'arbo', 38),
  c('tô com febre e muita fraqueza, suspeito de dengue', 'arbo', 45),
  c('minha filha tá com febre e reclamando de dor na barriga depois que a febre caiu', 'arbo', 9),

  // ── Violência e crise mental (10) ──
  c('meu marido me bateu e tô com medo de voltar pra casa', 'violencia', 34),
  c('fui forçada por um homem ontem à noite', 'violencia', 22, [], true),
  c('minha vizinha vive batendo nos filhos pequenos', 'violencia', 6),
  c('meu pai idoso tá sendo maltratado pela cuidadora', 'violencia', 82),
  c('tive uma relação sem camisinha e tenho medo de HIV', 'violencia', 27, [], true),
  c('meu namorado me ameaça e não me deixa sair', 'violencia', 25),
  c('tô ouvindo vozes que mandam eu fazer coisas', 'mentalgrave', 31),
  c('meu irmão surtou, tá agressivo e falando coisa sem sentido', 'mentalgrave', 28),
  c('parei de beber faz três dias e tô tremendo e vendo vulto', 'mentalgrave', 47),
  c('tô com vontade de me matar e já pensei como', 'mentalgrave', 39),

  // ── Vago e ruído (18) ──
  c('tô passando mal, não sei explicar', 'vago', 44),
  c('não tô bom, doutor', 'vago', 66),
  c('me sinto esquisita hoje', 'vago', 38),
  c('tô ruim das ideias', 'vago', 55),
  c('sinto uma coisa estranha no corpo', 'vago', 49),
  c('não tô legal, tô meio adoentada', 'vago', 58),
  c('deu uma coisa ruim em mim de manhã', 'vago', 62),
  c('tô meio zonzo e sem jeito', 'vago', 51),
  c('não sei o que tenho, só sei que tô mal', 'vago', 34),
  c('minha filha tá diferente, meio quieta', 'vago', 10),
  c('vim ver o que pode ser isso que sinto', 'vago', 47),
  c('to com uma coisa ruim no estomago faiz dias', 'ruido', 40),
  c('minha cabesa ta doendo mutio', 'ruido', 33),
  c('to com febri e o corpo doendo', 'ruido', 29),
  c('nao to consigindo respira direito', 'ruido', 60, ['asma_dpoc']),
  c('minha preção ta muinto alta', 'ruido', 58, ['hipertensao']),
  c('meu fío ta com muita febri e mole', 'ruido', 3),
  c('doi o peito e to suando frio', 'ruido', 56, ['hipertensao'], true),
];
